name: Python application

on:
 push:
  branches:
   - "main"
 pull_request:
  branches:
   - "main"
 workflow_dispatch:
  inputs:
   version:
    description: 'Version for the release'
    required: true

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    python-version: [ "3.10", "3.11", "3.12" ]
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Python
     uses: actions/setup-python@v4
     with:
      python-version: ${{ matrix.python-version }}

   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      pip install flake8 pytest
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

   - name: Lint with flake8
     run: |
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

   - name: Test with pytest
     run: pytest test_app.py

 publish:
  runs-on: ubuntu-latest
  needs: test
  if: ${{ github.event_name == 'workflow_dispatch' }}
  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Create zip file
     run: |
      cd ..
      zip -r release.zip * -x .git/\* -x .github/\* -x release.zip -x .gitignore -x .gitattributes -x .DS_Store -x .editorconfig -x .vscode/\* -x .idea/\*
      mv release.zip ${{ github.workspace }}/release.zip
   - name: Release
     id: release
     uses: softprops/action-gh-release@v2
     with:
      tag_name: ${{ github.event.inputs.version }}
      name: Release ${{ github.event.inputs.version }}
      files: release.zip
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
